# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
           python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudformation-cli cloudformation-cli-java-plugin cloudformation-cli-go-plugin cloudformation-cli-python-plugin --upgrade
          cfn --version
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file opsgenie_user/pom.xml
      - name: Configure Git user
        run: |
          git config user.email "trabab@atlassian.com"
          git config user.name "trabab"
      - name: Publish JAR
        run: |
          mvn -B versions:set -DnewVersion=1.0.9 -DgenerateBackupPoms=false --file opsgenie_user/pom.xml
          git status
          git add opsgenie_user/pom.xml
          git status
          git commit -m "test"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_API_KEY }}
      - id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
          bump: patch
          prefix: api_server_v
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.next_version.outputs.version }}



